### ISSUE TITLE
PlebNet kickoff

### ISSUE THREAD

**Issue by andrebreis** [MattSkala/PlebNet#1]
First: install plebnet on a virtual box - environment? @MattSkala  @HusainKapadia 

Problems?

**Comment by MattSkala** [comment]
I've been able to setup PlebNet on Ubuntu 16.04. Probably the easiest way to create a virtual machine locally is using [Vagrant](https://www.vagrantup.com/) with the VirtualBox provider:
```
vagrant init bento/ubuntu-16.04
vagrant up
vagrant ssh
```

Alternatively, I think you can just use LXC/Docker on Ubuntu.

Download the install script:
```
wget https://raw.githubusercontent.com/MattSkala/PlebNet/develop/plebnet/clone/install.sh
```

Run the install script with arguments `develop` (clone MattSkala/PlebNet#develop branch) `0` (do not start exit node) `0` (do not use BTC Testnet):
```
sudo bash install.sh develop 0 0
```
It clones the PlebNet repository into `~`, installs required dependencies and runs `plebnet setup` with provided parameters.

You should find the following output in `/root/plebnet.log`:
```
                : Setting up PlebNet
init_irc_client : the IRC client is initializing
init_irc_client : the IRC client is initialized
start_irc_cli.. : the IRC client is starting
start_irc_cli.. : the IRC client is started
                : tree set to plebbot5410
                : PlebNet is ready to roll!
```

Notes:
- `PlebNet` needs to be cloned into `~`, because `init_path` is harcoded in https://github.com/MattSkala/PlebNet/blob/7fbbb13066f1de6136e3272227b722df7e7e1f1c/plebnet/settings/plebnet_settings.py#L25
- If `~/.config` dir did not exist, `plebnet setup` failed. Fixed in 544345db08f2980b17b8ab11d1c404bf2fa8e541
- Python 2.7 is used
- The directory structure of cloudomate probably prevents the submodule from being imported in PyCharm?

**Comment by MattSkala** [comment]
Problem:
```$ plebnet check```
```/usr/bin/twistd: Unknown command: plebnet```

**Comment by HusainKapadia** [comment]
I did not get this error but there were some import errors. 
Try changing the permissions of the .config folder to use the plebnet command

**Comment by MattSkala** [comment]
We need to be able to start Tribler headless with an exit node and a marketplace using Bitcoin Testnet. [Tribler provides 3 plugins](https://github.com/Tribler/tribler/tree/devel/twisted/plugins) for Twisted (a networking engine), but I think none of them does all we need. I have found [the plugin created by the previous group](https://github.com/HvanVeltom/tribler/blob/06bbe570e186738e5e1412935e16a5adc43d796c/twisted/plugins/plebnet_plugin.py), so we might use it as the basis for our plugin, and update it to work with the latest Tribler#master.

References:
[Writing a twistd Plugin](https://twistedmatrix.com/documents/current/core/howto/tap.html)

**Comment by MattSkala** [comment]
I added the plugin in https://github.com/MattSkala/PlebNet/commit/a13e2693436583396650625a1966a80ea1645f43 and now Tribler is able to run. But I'm getting the following error when trying to create a wallet on the second run of `plebnet check`:
```
2018-12-01T11:56:59+0000 [stderr#error] ERROR:RESTRequest:[Failure instance: Traceback: <type 'exceptions.KeyError'>: 'TBTC'
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/twisted/web/http.py:2115:_finishRequestBody
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/twisted/web/http.py:2190:allContentReceived
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/twisted/web/http.py:917:requestReceived
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/Tribler/Core/Modules/restapi/rest_manager.py:96:process
2018-12-01T11:56:59+0000 [stderr#error] --- <exception caught here> ---
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/twisted/web/server.py:199:process
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/twisted/web/server.py:259:render
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
2018-12-01T11:56:59+0000 [stderr#error] /usr/local/lib/python2.7/dist-packages/Tribler/Core/Modules/restapi/wallets_endpoint.py:116:render_PUT
2018-12-01T11:56:59+0000 [stderr#error] ]
2018-12-01T11:56:59+0000 [stderr#error] Traceback (most recent call last):
2018-12-01T11:56:59+0000 [stderr#error]   File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 199, in process
2018-12-01T11:56:59+0000 [stderr#error]     self.render(resrc)
2018-12-01T11:56:59+0000 [stderr#error]   File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 259, in render
2018-12-01T11:56:59+0000 [stderr#error]     body = resrc.render(self)
2018-12-01T11:56:59+0000 [stderr#error]   File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
2018-12-01T11:56:59+0000 [stderr#error]     return m(request)
2018-12-01T11:56:59+0000 [stderr#error]   File "/usr/local/lib/python2.7/dist-packages/Tribler/Core/Modules/restapi/wallets_endpoint.py", line 116, in render_PUT
2018-12-01T11:56:59+0000 [stderr#error]     if self.session.lm.wallets[self.identifier].created:
2018-12-01T11:56:59+0000 [stderr#error] KeyError: 'TBTC'
2018-12-01T11:56:59+0000 [twisted.python.log#info] "127.0.0.1" - - [01/Dec/2018:11:56:58 +0000] "PUT /wallets/TBTC HTTP/1.1" 500 641 "-" "python-requests/2.9.1"
```

**Comment by MattSkala** [comment]
The problem is that `bitcoinlib` cannot be imported by Tribler for some reason. I found the following error in `plebnet/twistd.log`:
`ERROR:TriblerLaunchMany:bitcoinlib library cannot be found, Bitcoin wallet not available!`
https://github.com/Tribler/tribler/blob/7c9d92b6586b46ce44eac53e5bc2b4c2a8e81732/Tribler/Core/APIImplementation/LaunchManyCore.py#L442

However, the library is installed:
`$ pip install python-bitcoinlib`
`Requirement already satisfied: python-bitcoinlib in /usr/local/lib/python2.7/dist-packages (0.10.1)`

**Comment by MattSkala** [comment]
I was using the wrong `python-bitcoinlib`, the right one is `bitcoinlib` 🤦‍♂️ 

Note that the version `0.4.1` has to be used, because with the latest `0.4.2` you get the following error:

```
2018-12-01 14:17:23+0000 [-] Traceback (most recent call last):
2018-12-01 14:17:23+0000 [-]   File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
2018-12-01 14:17:23+0000 [-]     self.render(resrc)
2018-12-01 14:17:23+0000 [-]   File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
2018-12-01 14:17:23+0000 [-]     body = resrc.render(self)
2018-12-01 14:17:23+0000 [-]   File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
2018-12-01 14:17:23+0000 [-]     return m(request)
2018-12-01 14:17:23+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/Core/Modules/restapi/wallets_endpoint.py", line 124, in render_PUT
2018-12-01 14:17:23+0000 [-]     self.session.lm.wallets[self.identifier].create_wallet().addCallback(on_wallet_created)
2018-12-01 14:17:23+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/Tribler/Core/Modules/wallet/btc_wallet.py", line 59, in create_wallet
2018-12-01 14:17:23+0000 [-]     self.wallet = HDWallet.create(self.wallet_name, network=self.network, databasefile=self.db_path)
2018-12-01 14:17:23+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/bitcoinlib/wallets.py", line 942, in create
2018-12-01 14:17:23+0000 [-]     witness_type=witness_type, multisig=multisig)
2018-12-01 14:17:23+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/bitcoinlib/wallets.py", line 353, in from_key
2018-12-01 14:17:23+0000 [-]     witness_type=witness_type, multisig=multisig, is_private=True)).first()
2018-12-01 14:17:23+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/bitcoinlib/keys.py", line 1146, in wif
2018-12-01 14:17:23+0000 [-]     prefix = self.network.wif_prefix(is_private=True, witness_type=witness_type, multisig=multisig)
2018-12-01 14:17:23+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/bitcoinlib/networks.py", line 246, in wif_prefix
2018-12-01 14:17:23+0000 [-]     script_type = script_type_default(witness_type, multisig, locking_script=True)
2018-12-01 14:17:23+0000 [-] NameError: global name 'script_type_default' is not defined
```

Also, I updated Tribler submodule to the latest commit in the `devel` branch, as the compatibility with `0.4.1` was fixed recently in https://github.com/Tribler/tribler/pull/4003

**Comment by andrebreis** [comment]
> Alternatively, I think you can just use LXC/Docker on Ubuntu.
> 
> Download the install script:
> 
> ```
> wget https://raw.githubusercontent.com/MattSkala/PlebNet/develop/plebnet/clone/install.sh
> ```
> Run the install script with arguments `develop` (clone MattSkala/PlebNet#develop branch) `0` (do not start exit node) `1` (use BTC Testnet):

I just ran this and it worked

**Comment by HusainKapadia** [comment]
When is run `plebnet check` 
I get the following error:
```
agent.core      : Checking PlebNet
  PID TTY          TIME CMD
                : No VPN configurations found!
Plebnet Check   : !!! VPN is not installed, child may get banned !!!
agent.core      : Tribler is already running
agent.core      : No provider chosen yet
agent.core      : Provider chosen: None
agent.core      : Calculating new offer
                : An error occured!
                : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plebnet/cmdline.py", line 41, in execute
    args.func()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/cmdline.py", line 66, in execute_check
    agent.check()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/agent/core.py", line 108, in check
    attempt_purchase()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/agent/core.py", line 216, in attempt_purchase
    (provider, option, _) = config.get('chosen_provider')
TypeError: 'NoneType' object is not iterable
```

**Comment by MattSkala** [comment]
@HusainKapadia That happens when cloudomate returns no options for some of the providers. I just updated cloudomate submodule to the latest develop, so it should be working now.

**Comment by rpytel1** [comment]
@MattSkala  you managed to make ```plebnet check``` two times? I get nice and going on the first time but at the second time I get some errors: 
```
vagrant@vagrant:~$ sudo plebnet check
agent.core      : Checking PlebNet
  PID TTY          TIME CMD
                : No VPN configurations found!
Plebnet Check   : !!! VPN is not installed, child may get banned !!!
agent.core      : Tribler is already running
                : create Testnet wallet
create_wallet   : Wallet created successfully
agent.core      : No provider chosen yet
                : An error occured!
                : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plebnet/cmdline.py", line 41, in execute
    args.func()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/cmdline.py", line 66, in execute_check
    agent.check()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/agent/core.py", line 103, in check
    select_provider()
  File "/usr/local/lib/python2.7/dist-packages/plebnet/agent/core.py", line 317, in select_provider
    choice = cloudomate_controller.pick_provider(providers)
  File "/usr/local/lib/python2.7/dist-packages/plebnet/controllers/cloudomate_controller.py", line 117, in pick_provider
    option, price, currency = pick_option(provider)
  File "/usr/local/lib/python2.7/dist-packages/plebnet/controllers/cloudomate_controller.py", line 129, in pick_option
    vps_options = options(cloudomate_providers['vps'][provider])
  File "/usr/local/lib/python2.7/dist-packages/plebnet/controllers/cloudomate_controller.py", line 102, in options
    return provider.get_options()
  File "/usr/local/lib/python2.7/dist-packages/cloudomate/hoster/vps/proxhost.py", line 101, in get_options
    response = request.urlopen(url, context=context)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by HusainKapadia** [comment]
@MattSkala I pulled your change. I get the same error. No vpn configs found

**Comment by MattSkala** [comment]
@rpytel1 I'm able to run it when the plebnet is installed without the testnet parameter. (You can just rerun `plebnet setup` without any parameters once you have all the dependencies installed, you do not need to run the whole installation again.) 

For testnet, the only available provider is proxhost, which is a simulated vps provider used for end-to-end testing, but we do not know how to run it. In the [PlebNet 2018 report](https://repository.tudelft.nl/islandora/object/uuid%3A614efc19-e6a9-453f-8084-2e2c54ddd93f), it is mentioned it can be run using some Ansible scripts, but I haven't found them anywhere.

**Comment by MattSkala** [comment]
> @MattSkala I pulled your change. I get the same error. No vpn configs found

"No VPN configurations found!" message is expected, but the exception should be fixed.

`git pull` is not enough, make sure you also run `git submodule update` and `pip install ./cloudomate`.

**Comment by HusainKapadia** [comment]
We have the same error.

**Comment by MattSkala** [comment]
Try to `rm ~/.config/plebnet.json` and run `plebnet check` again.

**Comment by HusainKapadia** [comment]
No progress :(

**Comment by HusainKapadia** [comment]
We get the NoneType error mainly because our plebnet.json in the .config directory has a ´Null´ for the providers entry. 

Do we need to chose some vpn providers?

**Comment by rpytel1** [comment]
I tried it two times on completly fresh vm machine and still the same error. 
1. Install all according to the tutorial above
2. ```plebnet setup```
3. ```plebnet check```
4. ```plebnet check```(error)

**Comment by MattSkala** [comment]
I just found out this might happen when you install plebnet with testnet parameter and then try to setup without using testnet. Then the vps field in `~/config/DNA.json` stays empty and there are no providers to choose from.

So you need to:
1. `rm ~/.config/DNA.json`
2. `plebnet setup`
3. `plebnet check` should work

**Comment by rpytel1** [comment]
Perfecto! Works!
I will try to perform it on completly fresh VM to be sure.

**Comment by HusainKapadia** [comment]
Yes..worked for me as well...Thanks

**Comment by rpytel1** [comment]
It works perfectly even on fresh vm.

**Comment by andrebreis** [comment]
Everyone was able to setup plebnet successfully.

**Comment by MattSkala** [comment]
ProTip: You can add a synced folder to your `Vagrantfile` to share the code between the VM and host OS:
`config.vm.synced_folder "/Users/matt/PlebNet/plebnet", "/home/vagrant/PlebNet/plebnet"`

You can run plebnet from the source code in `~/PlebNet` like this: `python -m plebnet.cmdline check`

// @rpytel1 @HusainKapadia
